const lists = {
    "fresh-and-fruits": {
        id: "fresh-and-fruits",
        title: "Fresh Vegetables & Fruits",
        clarification: "For You",
        items: [
            {
                id: 1,
                title: "Product Title Here",
                img: "/img/products/product-7.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 2,
                title: "Product Title Here",
                img: "/img/products/product-2.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 3,
                title: "Product Title Here",
                img: "/img/products/product-3.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 4,
                title: "Product Title Here",
                img: "/img/products/product-4.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 5,
                title: "Product Title Here",
                img: "/img/products/product-5.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 6,
                title: "Product Title Here",
                img: "/img/products/product-5.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
        ],
    },
    "top-featured-products": {
        title: "Top Featured Products",
        clarification: "For You",
        id: "top-featured-products",
        items: [
            {
                id: 1,
                title: "Product Title Here",
                img: "/img/products/product-1.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 2,
                title: "Product Title Here",
                img: "/img/products/product-2.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 3,
                title: "Product Title Here",
                img: "/img/products/product-3.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 4,
                title: "Product Title Here",
                img: "/img/products/product-4.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 5,
                title: "Product Title Here",
                img: "/img/products/product-5.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 6,
                title: "Product Title Here",
                img: "/img/products/product-5.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 7,
                title: "Product Title Here",
                img: "/img/products/product-1.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 8,
                title: "Product Title Here",
                img: "/img/products/product-2.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 9,
                title: "Product Title Here",
                img: "/img/products/product-3.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 10,
                title: "Product Title Here",
                img: "/img/products/product-4.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 11,
                title: "Product Title Here",
                img: "/img/products/product-5.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 12,
                title: "Product Title Here",
                img: "/img/products/product-5.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
        ]
    },
    "added-new-products": {
        title: "Added New Products",
        clarification: "For You",
        id: "added-new-products",
        items: [
            {
                id: 1,
                title: "Product Title Here",
                img: "/img/products/product-6.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 2,
                title: "Product Title Here",
                img: "/img/products/product-2.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 3,
                title: "Product Title Here",
                img: "/img/products/product-3.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 4,
                title: "Product Title Here",
                img: "/img/products/product-4.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 5,
                title: "Product Title Here",
                img: "/img/products/product-5.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
            {
                id: 6,
                title: "Product Title Here",
                img: "/img/products/product-5.jpg",
                price: "12",
                oldPrice: "15",
                available: "Available (In Stock)",
                discount: "6%",
            },
        ]
    },
}
export default lists;